spring.application.name=crm-service
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/crm_db
spring.datasource.username=corrus
spring.datasource.password=corrus


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver