spring.application.name=crm-service
spring.datasource.url = jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username = admin
spring.datasource.password = admin

spring.jpa.hibenate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibenate.format_sql=true